### ISSUE TITLE
Async Ruby SDK

### ISSUE THREAD

**Issue by AllieW99** [GDATASoftwareAG/vaas#163]
**Actual:**

- Every time you send a request you need to wait to get a response before you can send the next one (synchronous)

**Expected:**

- You can send requests without waiting for the respond (asynchronous)
- Assign message to requests on respond

**TODO:**
- [x] Make the vaas_main.rb functions async
- [x] Add Keep-Alive
- [x] Add more Error-Handling
- [x] Error-Handling for upload status
- [x] Add timeouts for async-tasks
- [x] Adjust existing tests
- [x] Add more tests (big file, timeout)
- [x] Adjust examples
- [x] Adjust READMEs
